export const PEDIDO_FIND_BY_ID = 'PEDIDO_FIND_BY_ID';
export const DETALLE_PEDIDO_FIND_ALL_BY_ID_PEDIDO = 'DETALLE_PEDIDO_FIND_ALL_BY_ID_PEDIDO';
export const PEDIDO_PAGINATED_SEARCH = 'PEDIDO_PAGINATED_SEARCH';